solution
mate-academy/ts_figures_classes pull request #1245
Opened 2023-05-31 19:26 UTC by snuber-w

2023-06-01 16:22 UTC, naziamoff requested changes
good job 🔥 
Let's fix the errors issue and we're good

2023-06-01 16:22 UTC, naziamoff commented on src/figuresClasses.ts
> +const error = new Error('somethig went wrong');
no, you want your errors to be maximally descriptive. I as a user comes here - passed irrelevant input. I don't know what I did wrong. But I should know

2023-06-01 16:22 UTC, naziamoff commented on src/figuresClasses.ts
> +      && c < a + b;
should be separated into two different error messages

2023-06-02 07:38 UTC, 33Orange approved these changes
Well done !

2024-04-13 14:34 UTC, closed without merging