Hate LF and CRLF
mate-academy/ts_figures_classes pull request #219
Opened 2022-01-11 19:53 UTC by MaksimusCRS

2022-01-11 20:05 UTC, luckdenny commented on src/figuresClasses.ts
> +  constructor(public color: string, public radius: number) {
constructor(public color: Color, public radius: number) {   You have yourself custom type, use it

2022-01-11 20:05 UTC, luckdenny approved these changes

2022-01-11 20:06 UTC, MaksimusCRS commented on src/figuresClasses.ts
> +  constructor(public color: string, public radius: number) {
Да-да, полностью согласен, проглядел в одном месте его применить) Уже всё поправил)

2022-01-12 11:27 UTC, danheim requested changes
create enum

2022-01-12 11:27 UTC, danheim commented on src/figuresClasses.ts
> +type Shape = 'triangle' | 'circle' | 'rectangle';
it has to be an enum

2022-01-12 11:27 UTC, danheim commented on src/figuresClasses.ts
> +  shape: Shape = 'triangle';
avoid strings
```suggestion
  shape: Shape = Shape.Triangle;
```

2022-01-12 11:27 UTC, danheim commented on src/figuresClasses.ts
> +  shape: string;
enum, not string

2022-01-13 08:06 UTC, danheim approved these changes

2022-10-20 17:48 UTC, closed without merging