implemented solution
mate-academy/ts_figures_classes pull request #678
Opened 2022-10-05 19:22 UTC by SerhiiRomaniukWD

2022-10-07 14:01 UTC, xiimiik approved these changes
GJ 🔥

2022-10-08 06:53 UTC, Anna-Tkachenko requested changes

2022-10-08 06:53 UTC, Anna-Tkachenko commented on src/figuresClasses.ts
> +}
Check checklist

2022-10-10 08:06 UTC, Denchepornyuk approved these changes

2025-05-25 17:23 UTC, closed without merging